# Generated by Django 4.0.4 on 2022-05-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='DateOfJoining',
            new_name='dateOfJoining',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='contact_number',
            new_name='contact',
        ),
    ]
