# Generated by Django 4.0.4 on 2022-07-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_dateofjoining_employee_dateofjoining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='warranty',
            name='purchase',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
